### ISSUE TITLE
__ATOMIC_RELAXED vs. __ATOMIC_ACQUIRE

### ISSUE THREAD

**Issue by dvicini** [mitsuba-renderer/nanothread#8]
Hi Wenzel,

I was told that that the `__atomic_compare_exchange` call in `queue.cpp` should use `__ATOMIC_ACQUIRE` on failure, instead of the current `__ATOMIC_RELAXED`. I (still) don't quite understand how those fences work, but was told that this currently looks to be a bug.

Modifying this fixed some of the TSAN errors we have been seeing for us. I didn't notice a performance difference when running the MItsuba test suite, but also didn't benchmark thoroughly

**Comment by wjakob** [comment]
Thank you for the report, I changed this on the `master` and `nanobind` branches of this repository. In most cases, a failure is followed by a load-acquire, which IIRC would do the same thing. But looking through the code, it's not done consistently everywhere, so your unnamed colleague likely has a point.

There is no harm in increasing the strength of the memory ordering requirement. It will not change code generation on x86, which lacks weakly ordered memory operation. But on M1 macs and other aarch64 machines, there may be an impact (and ditto for TSAN that is probably analyzing very carefully with what memory order parameters these operations are invoked.)
